sudo: false
language: ruby
rvm:
- 2.2.0
- 2.2.1
- 2.2.2
- 2.2.3
- 2.3.0
before_install: gem install bundler
install: bundle install
script: bundle exec rake
bundler_args: "--without docs release repl"
